### ISSUE TITLE
strange serial monitor output

### ISSUE THREAD

**Issue by cstefan123** [gtalusan/esp32-i2s-sd#1]
Hello im having problems with the sketch, it gives me this output on serial monitor
![image](https://github.com/gtalusan/esp32-i2s-sd/assets/148694376/bd3c570b-1a38-48d7-a997-0c64bcc9182d)

**Comment by gtalusan** [comment]
Hello, this repository is fairly outdated.. however, please ensure your terminal program is set to 115200, or change the script such that it matches what your terminal is set to.

Thanks!
